{
  "type": "record",
  "namespace": "com.souqstation.shared.models",
  "name": "Publisher",
  "doc": "Modèle d'éditeur/studio de jeu",
  "fields": [
    {
      "name": "publisherId",
      "type": "string",
      "doc": "Identifiant unique de l'éditeur"
    },
    {
      "name": "name",
      "type": "string",
      "doc": "Nom de l'éditeur"
    },
    {
      "name": "country",
      "type": [
        "null",
        "string"
      ],
      "default": null,
      "doc": "Pays d'origine de l'éditeur"
    },
    {
      "name": "createdAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      },
      "doc": "Date d'enregistrement de l'éditeur"
    }
  ]
}
