plugins {
    id 'java'
}

allprojects {
    group = 'com.souqstation'
    version = '0.1.0'
    repositories {
        mavenCentral()
        maven { url "https://packages.confluent.io/maven/" }
    }
}

subprojects {
    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
    }
}
