server:
  port: 8082

spring:
  application:
    name: publisher-service

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8085
    consumer:
      group-id: publisher-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8085
        specific.avro.reader: false
    listener:
      ack-mode: manual

souq:
  topics:
    publisher: souq.publisher.events
    platform: souq.platform.events
