server:
  port: 8081
  error:
    include-message: always
    include-stacktrace: always

spring:
  application:
    name: platform-service
  datasource:
    url: jdbc:postgresql://localhost:5432/souq
    username: souq
    password: souq
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: platform-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      properties:
        schema.registry.url: http://localhost:8085
        specific.avro.reader: true
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      properties:
        schema.registry.url: http://localhost:8085
        value.subject.name.strategy: io.confluent.kafka.serializers.subject.RecordNameStrategy
    listener:
      ack-mode: manual

souq:
  topics:
    publisher: souq.publisher.events
    publisher-patch: souq.publisher.patch.events
  kafka:
    topics:
      platform:
        user: souq.platform.user.events
        redactor: souq.platform.redactor.events
        purchase: souq.platform.purchase.events
        review: souq.platform.review.events
        review-rated: souq.platform.review-rated.events
        incident: souq.platform.incident.events
