{
  "type": "record",
  "namespace": "com.souqstation.shared.events",
  "name": "GamePublishedEvent",
  "doc": "Événement : Jeu publié",
  "fields": [
    {
      "name": "eventId",
      "type": "string",
      "doc": "Identifiant unique de l'événement"
    },
    {
      "name": "eventType",
      "type": "string",
      "default": "game.published",
      "doc": "Type d'événement"
    },
    {
      "name": "occurredAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      },
      "doc": "Timestamp d'occurrence"
    },
    {
      "name": "schemaVersion",
      "type": "int",
      "default": 1,
      "doc": "Version du schéma"
    },
    {
      "name": "gameId",
      "type": "string",
      "doc": "Identifiant unique du jeu publié"
    },
    {
      "name": "name",
      "type": "string",
      "doc": "Nom du jeu"
    },
    {
      "name": "description",
      "type": [
        "null",
        "string"
      ],
      "default": null,
      "doc": "Description du jeu"
    },
    {
      "name": "publisherId",
      "type": "string",
      "doc": "Identifiant de l'éditeur"
    },
    {
      "name": "genres",
      "type": {
        "type": "array",
        "items": {
          "type": "enum",
          "namespace": "com.souqstation.shared.events.enums",
          "name": "GameGenre",
          "symbols": [
            "SIMULATION",
            "STRATEGIE",
            "JEUX",
            "ACTION",
            "RPG",
            "PUZZLE",
            "SPORTS",
            "AVENTURE"
          ]
        }
      },
      "doc": "Genres du jeu"
    },
    {
      "name": "platforms",
      "type": {
        "type": "array",
        "items": {
          "type": "enum",
          "namespace": "com.souqstation.shared.events.enums",
          "name": "Platform",
          "symbols": [
            "PC",
            "PS5",
            "EN_LIGNE"
          ]
        }
      },
      "doc": "Plateformes de sortie"
    },
    {
      "name": "version",
      "type": "string",
      "doc": "Version initiale du jeu"
    },
    {
      "name": "price",
      "type": [
        "null",
        "double"
      ],
      "default": null,
      "doc": "Prix du jeu"
    },
    {
      "name": "releaseDate",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      },
      "doc": "Date de sortie"
    }
  ]
}
