{
  "type": "record",
  "namespace": "com.souqstation.schemas.models",
  "name": "Purchase",
  "doc": "Modèle de transaction d'achat (jeu ou DLC)",
  "fields": [
    {
      "name": "purchaseId",
      "type": "string",
      "doc": "Identifiant unique de la transaction"
    },
    {
      "name": "userId",
      "type": "string",
      "doc": "Identifiant de l'acheteur"
    },
    {
      "name": "itemId",
      "type": "string",
      "doc": "Identifiant de l'article acheté (gameId ou dlcId)"
    },
    {
      "name": "itemType",
      "type": {
        "type": "enum",
        "namespace": "com.souqstation.schemas.models.enums",
        "name": "PurchaseItemType",
        "symbols": [
          "GAME",
          "DLC"
        ]
      },
      "doc": "Type d'article acheté"
    },
    {
      "name": "itemName",
      "type": "string",
      "doc": "Nom de l'article acheté"
    },
    {
      "name": "publisherId",
      "type": "string",
      "doc": "Identifiant de l'éditeur"
    },
    {
      "name": "price",
      "type": "double",
      "doc": "Prix payé"
    },
    {
      "name": "purchasedAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      },
      "doc": "Date et heure de l'achat"
    },
    {
      "name": "platform",
      "type": [
        "null",
        {
          "type": "enum",
          "namespace": "com.souqstation.schemas.models.enums",
          "name": "PurchasePlatform",
          "symbols": [
            "PC",
            "PS5",
            "EN_LIGNE"
          ]
        }
      ],
      "default": null,
      "doc": "Plateforme d'achat"
    }
  ]
}
