{
  "type": "record",
  "namespace": "com.souqstation.schemas.models",
  "name": "Review",
  "doc": "Modèle d'évaluation/critiques d'un jeu",
  "fields": [
    {
      "name": "reviewId",
      "type": "string",
      "doc": "Identifiant unique de l'évaluation"
    },
    {
      "name": "gameId",
      "type": "string",
      "doc": "Identifiant du jeu évalué"
    },
    {
      "name": "userId",
      "type": "string",
      "doc": "Identifiant de l'utilisateur qui a soumis l'évaluation"
    },
    {
      "name": "pseudo",
      "type": "string",
      "doc": "Pseudo de l'utilisateur"
    },
    {
      "name": "note",
      "type": "int",
      "doc": "Note donnée au jeu (0-10)"
    },
    {
      "name": "description",
      "type": [
        "null",
        "string"
      ],
      "default": null,
      "doc": "Description/commentaire de l'évaluation"
    },
    {
      "name": "createdAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      },
      "doc": "Date de soumission de l'évaluation"
    }
  ]
}
